name: Publish Docker image

on:
  push:
    branches:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Build image for commit
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ steps.commit.outputs.short }}
    
      
