name: testing-purpose

on:
  push:
    branches:
      - '*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: check Branch name and generate data in README file
        run: |
          echo  "new branch name is ${GITHUB_REF##*/}" >> README.md
          cat README.md
      - name: Commit files
        run: |
         git config --local user.email "erjattsingh@gmail.com"
         git config --local user.name "jatt-singh"
         git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         

          
