name: testing-purpose

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo new branch name is ${GITHUB_REF##*/}
      - name: Add data in readme file
        run: |
          git config --global user.email "erjattsingh@gmail.com"
          git config --global user.name "jatt-singh"
          git commit README.md -m  "new branch name is ${GITHUB_REF##*/}"
          cat README.md 
          
