name: testing-purpose

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: check Branch name
        run: echo new branch name is ${GITHUB_REF##*/}
      - name: Generate data in README file
        run:  echo  "new branch name is ${GITHUB_REF##*/}" >> README.md
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
