name: testing-purpose

on: push
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: check Branch name
        run: echo new branch name is ${GITHUB_REF##*/}
      - name: Generate data in README file
        run:  echo  "new branch name is ${GITHUB_REF##*/}" >> README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Apply changes
         push_options: --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
