name: (axim-backend) end-to-end tests

on:
  push:
    branches:
      - main

jobs:
  end_to_end_test:
    name: axim Backend test python script end to end
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v
          
      - name: Wait for 360 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check The Domain is Work Or Not 
        run: |
          STATUS_CODE=$(curl \
                      --output /dev/null \
                      --silent \
                      --write-out "%{http_code}" \
                      "https://axim-backend.sandbox-london-b.fetch-ai.com")
        
          if (( STATUS_CODE == 200 )); then
            echo "website is working"
          else     
            echo "Website is down some error come! , got  $STATUS_CODE"
          fi
          
      - name: Run Python script
        if: ${{ success() }}  
        run: |
            echo "script is run successfully"
           
      - name: delete hem chart always
        if: ${{ always() }}  
        run: |
            echo "helm chart is deleted"      
   
