name: (axim-backend) end-to-end tests

on:
  push:
    branches:
      - main

jobs:
  end_to_end_test:
    name: axim Backend test python script end to end
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  

      - name: Check The Domain is Work Or Not 
        run: |
         secs=60                         # Set interval (duration) in seconds.
         endTime=$(( $(date +%s) + secs )) # Calculate end time.

         while [ $(date +%s) -lt $endTime ]; do  # Loop until interval has elapsed.
           STATUS_CODE=$(curl \
                      --output /dev/null \
                      --silent \
                      --write-out "%{http_code}" \
                      "https://axim-backend-testing.sandbox-london-b.fetch-ai.com")
         
         if (( STATUS_CODE == 200 )); then
            echo "website is working"
         else     
            echo "Website is down some error come! , got  $STATUS_CODE"
         fi
         
         done
         
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  
          
      - name: Run Python script
        if: ${{ success() }}  
        run: |
            echo "script is run successfully"
           
      - name: delete hem chart always
        if: ${{ always() }}  
        run: |
            echo "helm chart is deleted"      
   
